name: tattt
on:
  push:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-dotnet2@3
        with:
          dotnet-version: '8.0.x'
      -run: dotnet build
      -name: Login to GHCR
      run: echo "${{secrets.GITHUB_TOKEN}}" | docker login ghcr.io -u ${{github.actor}} --password-stdin
      -name: Build image
      run: docker build -t ghcr.io/${{github.repository}}:latest .
      -name: Push image
      run: docker push ghcr.io/${{github.repository}}:latest
